[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vishwas Raj Batham", email = "vishwasrajbatham.151@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.52",
]

